#!/bin/bash
set -e
cd "$(dirname "$0")/.."

if [[ $(ls bin/Instrumental*.nupkg) ]] && [ "$1" == "lazy" ]; then
  exit
fi

# check dependencies
which mono > /dev/null || (echo "mono must be installed"; exit 1)
which mcs > /dev/null  || (echo "mcs must be installed"; exit 1)

script/nuget install vendor/packages.config -o vendor
mkdir -p bin

references=""
mcs -sdk:45 \
  -r:$references \
  -target:library \
  -out:bin/Instrumental.dll \
  -recurse:'Instrumental.NET/*.cs' \
  -doc:bin/Instrumental.xml \
  -platform:anycpu

script/nuget pack -OutputDirectory bin/
