#!/bin/bash
set -e
cd "$(dirname "$0")/.."

if [[ $(ls bin/Instrumental*.nupkg) ]] && [ "$1" == "lazy" ]; then
  exit
fi

# check dependencies
which mono > /dev/null || (echo "mono must be installed"; exit 1)
which mcs > /dev/null  || (echo "mcs must be installed"; exit 1)

script/nuget install packages.config -o vendor
mkdir -p bin

script/compile

script/nuget pack Instrumental.nuspec -OutputDirectory bin/

script/check_version
